--------------------------------------------------------
-- Archivo creado  - jueves-diciembre-03-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence SEC_ADMIN
--------------------------------------------------------

   CREATE SEQUENCE  "AGENDAU"."SEC_ADMIN"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEC_CALENDARIOS
--------------------------------------------------------

   CREATE SEQUENCE  "AGENDAU"."SEC_CALENDARIOS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 7 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEC_EVENTOS
--------------------------------------------------------

   CREATE SEQUENCE  "AGENDAU"."SEC_EVENTOS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEC_GRUPOS
--------------------------------------------------------

   CREATE SEQUENCE  "AGENDAU"."SEC_GRUPOS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEC_INVITACIONES
--------------------------------------------------------

   CREATE SEQUENCE  "AGENDAU"."SEC_INVITACIONES"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEC_PERMISOS
--------------------------------------------------------

   CREATE SEQUENCE  "AGENDAU"."SEC_PERMISOS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEC_USUARIOS
--------------------------------------------------------

   CREATE SEQUENCE  "AGENDAU"."SEC_USUARIOS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 3 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table ADMINS
--------------------------------------------------------

  CREATE TABLE "AGENDAU"."ADMINS" 
   (	"OID_A" NUMBER(*,0), 
	"OID_U" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(256 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CALENDARIOS
--------------------------------------------------------

  CREATE TABLE "AGENDAU"."CALENDARIOS" 
   (	"OID_C" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(256 BYTE), 
	"DESCRIPCION" VARCHAR2(2048 BYTE), 
	"TIPOCALENDARIO" VARCHAR2(14 BYTE), 
	"ESPUBLICO" VARCHAR2(3 BYTE), 
	"OID_U" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EVENTOS
--------------------------------------------------------

  CREATE TABLE "AGENDAU"."EVENTOS" 
   (	"OID_E" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(256 BYTE), 
	"FECHA" DATE, 
	"HORAINICIO" DATE, 
	"HORAFIN" DATE,
	"DESCRIPCION" VARCHAR2(2048 BYTE), 
	"OID_C" NUMBER(*,0), 
	"OID_G" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table GRUPOS
--------------------------------------------------------

  CREATE TABLE "AGENDAU"."GRUPOS" 
   (	"OID_G" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(256 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table INVITACIONES
--------------------------------------------------------

  CREATE TABLE "AGENDAU"."INVITACIONES" 
   (	"OID_INV" NUMBER(*,0), 
	"OID_U" NUMBER(*,0), 
	"OID_E" NUMBER(*,0), 
	"INV_ACEPTADA" VARCHAR2(2 BYTE) DEFAULT 'NO'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PERMISOS
--------------------------------------------------------

  CREATE TABLE "AGENDAU"."PERMISOS" 
   (	"OID_PERM" NUMBER(*,0), 
	"OID_U" NUMBER(*,0), 
	"OID_C" NUMBER(*,0), 
	"TIPOPERMISO" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table USUARIOS
--------------------------------------------------------

  CREATE TABLE "AGENDAU"."USUARIOS" 
   (	"OID_U" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(256 BYTE), 
	"APELLIDOS" VARCHAR2(256 BYTE), 
	"TIPOUSUARIO" VARCHAR2(6 BYTE), 
	"UVUS" VARCHAR2(600 BYTE), 
	"PASS" VARCHAR2(256 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into AGENDAU.ADMINS
SET DEFINE OFF;
REM INSERTING into AGENDAU.CALENDARIOS
SET DEFINE OFF;
Insert into AGENDAU.CALENDARIOS (OID_C,NOMBRE,DESCRIPCION,TIPOCALENDARIO,ESPUBLICO,OID_U) values ('1','Calendario Examenes','Calendario creado por la administracion','OFICIAL','SI','1');
Insert into AGENDAU.CALENDARIOS (OID_C,NOMBRE,DESCRIPCION,TIPOCALENDARIO,ESPUBLICO,OID_U) values ('2','Calendario Practicas','Calendario creado por la administracion','OFICIAL','SI','2');
REM INSERTING into AGENDAU.EVENTOS
SET DEFINE OFF;
REM INSERTING into AGENDAU.GRUPOS
SET DEFINE OFF;
REM INSERTING into AGENDAU.INVITACIONES
SET DEFINE OFF;
REM INSERTING into AGENDAU.PERMISOS
SET DEFINE OFF;
REM INSERTING into AGENDAU.USUARIOS
SET DEFINE OFF;
Insert into AGENDAU.USUARIOS (OID_U,NOMBRE,APELLIDOS,TIPOUSUARIO,UVUS,PASS) values ('1','Julia','Ibañez Montero','ADMIN','julibamon@us.es','1234');
Insert into AGENDAU.USUARIOS (OID_U,NOMBRE,APELLIDOS,TIPOUSUARIO,UVUS,PASS) values ('2','Flora','Viegas Peñalosa','ADMIN','floviepen@us.es','1234');
--------------------------------------------------------
--  DDL for Index SYS_C006988
--------------------------------------------------------

  CREATE UNIQUE INDEX "AGENDAU"."SYS_C006988" ON "AGENDAU"."USUARIOS" ("OID_U") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C006989
--------------------------------------------------------

  CREATE UNIQUE INDEX "AGENDAU"."SYS_C006989" ON "AGENDAU"."USUARIOS" ("UVUS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C006994
--------------------------------------------------------

  CREATE UNIQUE INDEX "AGENDAU"."SYS_C006994" ON "AGENDAU"."CALENDARIOS" ("OID_C") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C006997
--------------------------------------------------------

  CREATE UNIQUE INDEX "AGENDAU"."SYS_C006997" ON "AGENDAU"."GRUPOS" ("OID_G") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007002
--------------------------------------------------------

  CREATE UNIQUE INDEX "AGENDAU"."SYS_C007002" ON "AGENDAU"."EVENTOS" ("OID_E") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007009
--------------------------------------------------------

  CREATE UNIQUE INDEX "AGENDAU"."SYS_C007009" ON "AGENDAU"."INVITACIONES" ("OID_INV") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007014
--------------------------------------------------------

  CREATE UNIQUE INDEX "AGENDAU"."SYS_C007014" ON "AGENDAU"."ADMINS" ("OID_A") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007020
--------------------------------------------------------

  CREATE UNIQUE INDEX "AGENDAU"."SYS_C007020" ON "AGENDAU"."PERMISOS" ("OID_PERM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger C_PERSONAL_ADMIN
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "AGENDAU"."C_PERSONAL_ADMIN" 
BEFORE INSERT ON CALENDARIOS 
REFERENCING NEW AS NEW
FOR EACH ROW
DECLARE 
  TIPO USUARIOS.TIPOUSUARIO%TYPE;
BEGIN
SELECT TIPOUSUARIO INTO TIPO FROM USUARIOS WHERE OID_U = :NEW.OID_U;
IF :NEW.TIPOCALENDARIO != 'OFICIAL' AND (TIPO = 'ADMIN') THEN
    RAISE_APPLICATION_ERROR
      (-20602,'Un usuario tipo ADMIN solo puede crear calendarios tipo OFICIAL');
END IF;
END;

/
ALTER TRIGGER "AGENDAU"."C_PERSONAL_ADMIN" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CREA_OID_ADMINS
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "AGENDAU"."CREA_OID_ADMINS" 
BEFORE INSERT ON ADMINS
FOR EACH ROW
BEGIN
  SELECT SEC_ADMIN.NEXTVAL INTO :NEW.OID_A FROM DUAL;
END;
/
ALTER TRIGGER "AGENDAU"."CREA_OID_ADMINS" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CREA_OID_CALENDARIO
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "AGENDAU"."CREA_OID_CALENDARIO" 
BEFORE INSERT ON CALENDARIOS
FOR EACH ROW
BEGIN
    SELECT SEC_CALENDARIOS.NEXTVAL INTO :NEW.OID_C FROM DUAL;
END;

/
ALTER TRIGGER "AGENDAU"."CREA_OID_CALENDARIO" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CREA_OID_EVENTO
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "AGENDAU"."CREA_OID_EVENTO" 
BEFORE INSERT ON EVENTOS
FOR EACH ROW
BEGIN
  SELECT SEC_EVENTOS.NEXTVAL INTO :NEW.OID_E FROM DUAL;
END;

/
ALTER TRIGGER "AGENDAU"."CREA_OID_EVENTO" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CREA_OID_GRUPO
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "AGENDAU"."CREA_OID_GRUPO" 
BEFORE INSERT ON GRUPOS
FOR EACH ROW
BEGIN
  SELECT SEC_GRUPOS.NEXTVAL INTO :NEW.OID_G FROM DUAL;
END;

/
ALTER TRIGGER "AGENDAU"."CREA_OID_GRUPO" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CREA_OID_INVITACION
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "AGENDAU"."CREA_OID_INVITACION" 
BEFORE INSERT ON INVITACIONES
FOR EACH ROW
BEGIN
  SELECT SEC_INVITACIONES.NEXTVAL INTO :NEW.OID_INV FROM DUAL;
END;

/
ALTER TRIGGER "AGENDAU"."CREA_OID_INVITACION" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CREA_OID_PERMISO
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "AGENDAU"."CREA_OID_PERMISO" 
BEFORE INSERT ON PERMISOS
FOR EACH ROW
BEGIN
  SELECT SEC_PERMISOS.NEXTVAL INTO :NEW.OID_PERM FROM DUAL;
END;

/
ALTER TRIGGER "AGENDAU"."CREA_OID_PERMISO" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CREA_OID_USUARIOS
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "AGENDAU"."CREA_OID_USUARIOS" 
BEFORE INSERT ON USUARIOS
FOR EACH ROW
BEGIN
  SELECT SEC_USUARIOS.NEXTVAL INTO :NEW.OID_U FROM DUAL;
END;
/
ALTER TRIGGER "AGENDAU"."CREA_OID_USUARIOS" ENABLE;
--------------------------------------------------------
--  DDL for Procedure CREA_ADMINS
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "AGENDAU"."CREA_ADMINS" 
    (OID_U IN ADMINS.OID_U%TYPE,
    NOMBRE IN ADMINS.NOMBRE%TYPE) AS 
BEGIN
  INSERT INTO ADMINS (OID_U, NOMBRE) 
  VALUES(OID_U, NOMBRE);
END CREA_ADMINS;

/
--------------------------------------------------------
--  DDL for Procedure CREA_CALENDARIO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "AGENDAU"."CREA_CALENDARIO" 
    (W_NOMBRE IN CALENDARIOS.NOMBRE%TYPE,
    W_DESCRIPCION IN CALENDARIOS.DESCRIPCION%TYPE,
    W_OID_U IN CALENDARIOS.OID_U%TYPE ) IS 
BEGIN
    INSERT INTO CALENDARIOS(NOMBRE,DESCRIPCION,TIPOCALENDARIO,ESPUBLICO,OID_U)
    VALUES(W_NOMBRE,W_DESCRIPCION,'NOCOMPARTIDO','NO',W_OID_U);
    COMMIT WORK;
END CREA_CALENDARIO;

/
--------------------------------------------------------
--  DDL for Procedure DA_PERMISO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "AGENDAU"."DA_PERMISO" 
    (W_OID_U IN USUARIOS.OID_U%TYPE,
    W_OID_C IN CALENDARIOS.OID_C%TYPE,
    PERM IN PERMISOS.TIPOPERMISO%TYPE)  AS 
BEGIN
  INSERT INTO PERMISOS(PERMISOS.OID_C, PERMISOS.OID_U, PERMISOS.TIPOPERMISO) VALUES(W_OID_C, W_OID_U, PERM);
END DA_PERMISO;

/
--------------------------------------------------------
--  DDL for Procedure EVENTOS_CALENDARIO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "AGENDAU"."EVENTOS_CALENDARIO" 
    (OID_U IN USUARIOS.OID_U%TYPE,
    OID_C IN CALENDARIOS.OID_C%TYPE) AS
BEGIN
  DECLARE
  CURSOR cu IS
  SELECT NOMBRE, FECHA, HORAINICIO, HORAFIN, TIPOEVENTO, DIACOMPLETO, DESCRIPCION FROM EVENTOS
  ORDER BY FECHA;
  BEGIN
  FOR fila IN cu LOOP
    SYS.DBMS_OUTPUT.PUT_LINE(fila.NOMBRE||' '||fila.HORAINICIO||' '
    ||fila.HORAFIN||' '||fila.TIPOEVENTO||' '||fila.DIACOMPLETO||' '||fila.DESCRIPCION);
    END LOOP;
  END;
END EVENTOS_CALENDARIO;

/
--------------------------------------------------------
--  DDL for Procedure FOLLOW_CALENDARIO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "AGENDAU"."FOLLOW_CALENDARIO" 
    (W_OID_U IN USUARIOS.OID_U%TYPE,
    W_OID_C IN CALENDARIOS.OID_C%TYPE) AS 
BEGIN
  DECLARE PUB CALENDARIOS.ESPUBLICO%TYPE;
BEGIN
  SELECT CALENDARIOS.ESPUBLICO INTO PUB FROM CALENDARIOS WHERE OID_C = W_OID_C;
  IF PUB = 'SI' THEN
   DA_PERMISO(W_OID_U, W_OID_C, 'VER');
  END IF;
  END;
END FOLLOW_CALENDARIO;

/
--------------------------------------------------------
--  DDL for Procedure INSERTAR_CALENDARIO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "AGENDAU"."INSERTAR_CALENDARIO" 
    (W_NOMBRE IN CALENDARIOS.NOMBRE%TYPE,
    W_DESCRIPCION IN CALENDARIOS.DESCRIPCION%TYPE,
    W_TIPOCALENDARIO IN CALENDARIOS.TIPOCALENDARIO%TYPE,
    W_ESPUBLICO IN CALENDARIOS.ESPUBLICO%TYPE,
    W_OID_U IN CALENDARIOS.OID_U%TYPE) AS 
BEGIN
  INSERT INTO CALENDARIOS VALUES(0, W_NOMBRE, W_DESCRIPCION, W_TIPOCALENDARIO, W_ESPUBLICO, W_OID_U);
END INSERTAR_CALENDARIO;

/
--------------------------------------------------------
--  DDL for Procedure INSERTAR_EVENTO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "AGENDAU"."INSERTAR_EVENTO" 
    (W_NOMBRE IN VARCHAR2,
    W_FECHA IN VARCHAR2,
    W_HORAINICIO IN VARCHAR2,
    W_HORAFIN IN VARCHAR2,
    W_TIPOEVENTO IN VARCHAR2,
    W_DIACOMPLETO IN VARCHAR2,
    W_DESCRIPCION IN VARCHAR2,
    W_OID_C IN VARCHAR2,
    W_OID_G IN VARCHAR2) AS 
BEGIN
  INSERT INTO EVENTOS VALUES(SEC_EVENTOS.nextval, w_nombre, w_fecha, w_horainicio, w_horafin, w_tipoevento,
  w_diacompleto, w_descripcion, w_oid_c, w_oid_g);
END INSERTAR_EVENTO;

/
--------------------------------------------------------
--  DDL for Procedure INSERTAR_USUARIO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "AGENDAU"."INSERTAR_USUARIO" 
    (W_NOMBRE IN USUARIOS.NOMBRE%TYPE,
    W_APELLIDOS IN USUARIOS.APELLIDOS%TYPE,
    W_UVUS IN USUARIOS.UVUS%TYPE,
    W_PASS IN USUARIOS.PASS%TYPE) IS
BEGIN
  INSERT INTO USUARIOS (OID_U, NOMBRE, APELLIDOS, TIPOUSUARIO, UVUS, PASS)
  VALUES (SEC_USUARIOS.NEXTVAL, W_NOMBRE, W_APELLIDOS, 'ALUMNO',W_UVUS, W_PASS);
END INSERTAR_USUARIO;

/
--------------------------------------------------------
--  DDL for Procedure MODIFICAR_EVENTO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "AGENDAU"."MODIFICAR_EVENTO" 
    (W_NOMBRE IN EVENTOS.NOMBRE%TYPE,
    W_FECHA IN EVENTOS.FECHA%TYPE,
    W_HORAINICIO IN EVENTOS.HORAINICIO%TYPE,
    W_HORAFIN IN EVENTOS.HORAFIN%TYPE,
    W_TIPOEVENTO IN EVENTOS.TIPOEVENTO%TYPE,
    W_DIACOMPLETO IN EVENTOS.DIACOMPLETO%TYPE,
    W_DESCRIPCION IN EVENTOS.DESCRIPCION%TYPE,
    W_OID_C IN EVENTOS.OID_C%TYPE) AS
BEGIN
DECLARE
BEGIN
  UPDATE EVENTOS SET NOMBRE = W_NOMBRE, FECHA = W_FECHA, HORAINICIO = W_HORAINICIO,
  HORAFIN = W_HORAFIN, TIPOEVENTO = W_TIPOEVENTO, DIACOMPLETO = W_DIACOMPLETO, DESCRIPCION = W_DESCRIPCION
  WHERE OID_C = W_OID_C;
END;
END MODIFICAR_EVENTO;

/
--------------------------------------------------------
--  DDL for Procedure UNFOLLOW_CALENDARIO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "AGENDAU"."UNFOLLOW_CALENDARIO" 
    (W_OID_C IN CALENDARIOS.OID_C%TYPE,
    W_OID_U IN USUARIOS.OID_U%TYPE) AS 
BEGIN
   DELETE FROM PERMISOS WHERE OID_U = W_OID_U AND OID_C = W_OID_C;
END UNFOLLOW_CALENDARIO;

/
--------------------------------------------------------
--  DDL for Function CONTAR_EVENTOS
--------------------------------------------------------

  CREATE OR REPLACE FUNCTION "AGENDAU"."CONTAR_EVENTOS" 
    (W_OID_C IN EVENTOS.OID_C%TYPE)
    RETURN NUMBER IS W_CUENTA_EVENTOS EVENTOS.OID_C%TYPE;
BEGIN
    SELECT COUNT(*) INTO W_CUENTA_EVENTOS FROM EVENTOS
        WHERE OID_C=W_OID_C;
    RETURN (W_CUENTA_EVENTOS);
END;

/
--------------------------------------------------------
--  DDL for Function NUM_CALENDARIOS
--------------------------------------------------------

  CREATE OR REPLACE FUNCTION "AGENDAU"."NUM_CALENDARIOS" 
    (W_OID_U IN USUARIOS.OID_U%TYPE) 
    RETURN NUMBER IS NUM INTEGER; 
BEGIN
  SELECT COUNT(*) INTO NUM FROM CALENDARIOS
  WHERE OID_U = W_OID_U;
  RETURN (NUM);
END NUM_CALENDARIOS;

/
--------------------------------------------------------
--  DDL for Function TIENE_PERMISO
--------------------------------------------------------

  CREATE OR REPLACE FUNCTION "AGENDAU"."TIENE_PERMISO" 
    (W_OID_U IN USUARIOS.OID_U%TYPE,
    W_OID_C IN CALENDARIOS.OID_C%TYPE) 
    RETURN VARCHAR2 AS PERMISO PERMISOS.TIPOPERMISO%TYPE;
BEGIN
  DECLARE PERM PERMISOS.TIPOPERMISO%TYPE;
BEGIN
  SELECT TIPOPERMISO INTO PERM FROM PERMISOS WHERE OID_C = W_OID_C AND OID_U = W_OID_U;
  RETURN PERM;
  END;
END TIENE_PERMISO;

/
--------------------------------------------------------
--  Constraints for Table ADMINS
--------------------------------------------------------

  ALTER TABLE "AGENDAU"."ADMINS" ADD PRIMARY KEY ("OID_A")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "AGENDAU"."ADMINS" MODIFY ("OID_U" NOT NULL ENABLE);
  ALTER TABLE "AGENDAU"."ADMINS" MODIFY ("OID_A" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CALENDARIOS
--------------------------------------------------------

  ALTER TABLE "AGENDAU"."CALENDARIOS" ADD PRIMARY KEY ("OID_C")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "AGENDAU"."CALENDARIOS" ADD CHECK (ESPUBLICO IN ('SI','NO')) ENABLE;
  ALTER TABLE "AGENDAU"."CALENDARIOS" ADD CHECK (TIPOCALENDARIO IN('COMPARTIDO','OFICIAL','NOCOMPARTIDO')) ENABLE;
  ALTER TABLE "AGENDAU"."CALENDARIOS" MODIFY ("OID_U" NOT NULL ENABLE);
  ALTER TABLE "AGENDAU"."CALENDARIOS" MODIFY ("OID_C" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EVENTOS
--------------------------------------------------------

  ALTER TABLE "AGENDAU"."EVENTOS" ADD PRIMARY KEY ("OID_E")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "AGENDAU"."EVENTOS" ADD CHECK (DIACOMPLETO IN ('SI','NO')) ENABLE;
  ALTER TABLE "AGENDAU"."EVENTOS" ADD CHECK (TIPOEVENTO IN ('PERIODICO','UNICO')) ENABLE;
  ALTER TABLE "AGENDAU"."EVENTOS" MODIFY ("OID_C" NOT NULL ENABLE);
  ALTER TABLE "AGENDAU"."EVENTOS" MODIFY ("OID_E" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table GRUPOS
--------------------------------------------------------

  ALTER TABLE "AGENDAU"."GRUPOS" ADD PRIMARY KEY ("OID_G")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "AGENDAU"."GRUPOS" MODIFY ("OID_G" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table INVITACIONES
--------------------------------------------------------

  ALTER TABLE "AGENDAU"."INVITACIONES" ADD PRIMARY KEY ("OID_INV")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "AGENDAU"."INVITACIONES" ADD CHECK (INV_ACEPTADA IN('SI','NO')) ENABLE;
  ALTER TABLE "AGENDAU"."INVITACIONES" MODIFY ("OID_E" NOT NULL ENABLE);
  ALTER TABLE "AGENDAU"."INVITACIONES" MODIFY ("OID_U" NOT NULL ENABLE);
  ALTER TABLE "AGENDAU"."INVITACIONES" MODIFY ("OID_INV" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PERMISOS
--------------------------------------------------------

  ALTER TABLE "AGENDAU"."PERMISOS" ADD PRIMARY KEY ("OID_PERM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "AGENDAU"."PERMISOS" ADD CHECK (TIPOPERMISO IN('VER','EDITAR','INVITAR')) ENABLE;
  ALTER TABLE "AGENDAU"."PERMISOS" MODIFY ("OID_C" NOT NULL ENABLE);
  ALTER TABLE "AGENDAU"."PERMISOS" MODIFY ("OID_U" NOT NULL ENABLE);
  ALTER TABLE "AGENDAU"."PERMISOS" MODIFY ("OID_PERM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USUARIOS
--------------------------------------------------------

  ALTER TABLE "AGENDAU"."USUARIOS" ADD UNIQUE ("UVUS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "AGENDAU"."USUARIOS" ADD PRIMARY KEY ("OID_U")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "AGENDAU"."USUARIOS" ADD CHECK (TIPOUSUARIO IN ('ALUMNO','ADMIN')) ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ADMINS
--------------------------------------------------------

  ALTER TABLE "AGENDAU"."ADMINS" ADD FOREIGN KEY ("OID_U")
	  REFERENCES "AGENDAU"."USUARIOS" ("OID_U") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CALENDARIOS
--------------------------------------------------------

  ALTER TABLE "AGENDAU"."CALENDARIOS" ADD FOREIGN KEY ("OID_U")
	  REFERENCES "AGENDAU"."USUARIOS" ("OID_U") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EVENTOS
--------------------------------------------------------

  ALTER TABLE "AGENDAU"."EVENTOS" ADD FOREIGN KEY ("OID_C")
	  REFERENCES "AGENDAU"."CALENDARIOS" ("OID_C") ON DELETE CASCADE ENABLE;
  ALTER TABLE "AGENDAU"."EVENTOS" ADD FOREIGN KEY ("OID_G")
	  REFERENCES "AGENDAU"."GRUPOS" ("OID_G") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table INVITACIONES
--------------------------------------------------------

  ALTER TABLE "AGENDAU"."INVITACIONES" ADD FOREIGN KEY ("OID_U")
	  REFERENCES "AGENDAU"."USUARIOS" ("OID_U") ENABLE;
  ALTER TABLE "AGENDAU"."INVITACIONES" ADD FOREIGN KEY ("OID_E")
	  REFERENCES "AGENDAU"."EVENTOS" ("OID_E") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PERMISOS
--------------------------------------------------------

  ALTER TABLE "AGENDAU"."PERMISOS" ADD FOREIGN KEY ("OID_U")
	  REFERENCES "AGENDAU"."USUARIOS" ("OID_U") ON DELETE SET NULL ENABLE;
  ALTER TABLE "AGENDAU"."PERMISOS" ADD FOREIGN KEY ("OID_C")
	  REFERENCES "AGENDAU"."CALENDARIOS" ("OID_C") ON DELETE SET NULL ENABLE;
